easy_admin:
    site_name: 'CACES<br>admin'
    user:
        display_name: true
        name_property_path: 'lastname'
    design:
        brand_color: '#23FE01'
    entities:
        User:
            class: App\Entity\User
            edit:
                fields:
                    - { property: 'firstname', type: 'text'}
                    - { property: 'lastname', type: 'text'}
                    - { property: 'email', type: 'email'}
                    - { property: 'role', type: 'text'}
            new:
                fields:
                    - { property: 'firstname', type: 'text'}
                    - { property: 'lastname', type: 'text'}
                    - { property: 'email', type: 'email'}
                    - { property: 'password', type: 'password'}
                    - { property: 'role', type: 'text'}
        Lesson:
            class: App\Entity\Lesson
            edit:
                fields:
                    - { property: 'Chapter', type: 'text', label: 'Chapitre'}
                    - { property: 'Part', type: 'text'}
                    - { property: 'title', type: 'text', label: 'Titre'}
                    - { property: 'Video', type: 'text'}
                    - { property: 'T1', type: 'text', label: 'Titre 1'}
                    - { property: 'P1', type: 'textarea', label: 'Paragraphe 1'}
                    - { property: 'T2', type: 'text', label: 'Titre 2'}
                    - { property: 'P2', type: 'textarea', label: 'Paragraphe 2'}
                    - { property: 'T3', type: 'text', label: 'Titre 3'}
                    - { property: 'P3', type: 'textarea', label: 'Paragraphe 3'}
                    - { property: 'idLesson', type: 'text'}
            new:
                fields:
                    - { property: 'Chapter', type: 'text', label: 'Chapitre'}
                    - { property: 'Part', type: 'text'}
                    - { property: 'title', type: 'text', label: 'Titre'}
                    - { property: 'Video', type: 'text'}
                    - { property: 'T1', type: 'text', label: 'Titre 1'}
                    - { property: 'P1', type: 'textarea', label: 'Paragraphe 1'}
                    - { property: 'T2', type: 'text', label: 'Titre 2'}
                    - { property: 'P2', type: 'textarea', label: 'Paragraphe 2'}
                    - { property: 'T3', type: 'text', label: 'Titre 3'}
                    - { property: 'P3', type: 'textarea', label: 'Paragraphe 3'}
                    - { property: 'idLesson', type: 'text'}

        Question:
            class: App\Entity\Question
        News:
            class: App\Entity\News